### PR TITLE
fix(unicorn): add special thread for closing connections to avoid dea…

### PR DESCRIPTION
**Pull request by antmat**
If connection is loss and reestablished from ZK callback that can lead to inifinite join and deadlock.
I don't see a better way now, except closing connections in a separate thread.

### CODE REVIEW

**Comment by antmat** [comment]
@3Hren PTAL

**Comment by 3Hren** [comment]
Bad abstraction. Implement loop executor.

**Comment by antmat** [comment]
What exactly do you mean? Why do we need an abstraction inside connection implementation? it's implementation details.

**Comment by 3Hren** [comment]
Nevermind. Do not distracting you from making your code look like garbage anymore. Implementation details == shit?

**Comment by antmat** [comment]
Nope, but I still don't get your point. 
I defer cleanup to a separate thread, do it once only in one place. Why do I need an abstraction there?

**Comment by 3Hren** [comment]
Because it simplifies reading your code. Moreover it's more about decomposition, class coupling, cohesion and other class metrics.

**Pull request merged**
