### PR TITLE
fix(node): fix race with invalid state

### PR DESCRIPTION
**Pull request by 3Hren**
@antmat PTAL.

### CODE REVIEW

**Comment by 3Hren** [comment]
@antmat @noxiouz PTAL again, maybe I missed something.

**Comment by noxiouz** [comment]
+1

**Comment by antmat** [comment]
LGTM in fact, sorry for delay

**Comment by 3Hren** [comment]
It's a quite tricky change, so it must be deployed as a single change in the version to be sure that nothing interferes with it if sometimes goes bad

**Pull request closed without merging**
